### PR TITLE
Fixes #34 - Phoenix 1.3-rc compatability

### LINKED ISSUE #34: Make slime compatible with phoenix > 1.3.0-rc.0
Failed to use "phoenix" (version 1.3.0-rc.0) because
      phoenix_slime (version 0.8.0) requires ~> 1.2 *
      mix.exs specifies ~> 1.3.0-rc

If I can manage to find the time tomorrow, I'll make a PR. I guess we should just update the mix file and the readme paths. Maybe the generator too, I'll check that.

### PR DESCRIPTION
**Pull request by wulymammoth**
- credit goes to [KazW](https://github.com/slime-lang/phoenix_slime/pull/35) for leading the effort
- addressing the Phoenix alias of `:datetime` for `:naive_datetime` [source](https://github.com/phoenixframework/phoenix/blob/master/lib/mix/tasks/phx.gen.schema.ex#L30)

### CODE REVIEW

**Comment by wulymammoth** [comment]
Wondering if we want to consider a version bump for this (lack of backward compatibility)

File: mix.exs [hunk 1]
```diff
@@ -20,7 +20,7 @@ defmodule PhoenixSlime.Mixfile do
   end
 
   def deps do
-    [{:phoenix, "~> 1.2"},
+    [{:phoenix, "~> 1.3-rc"},
```
Comment (doomspork) [inline mix.exs:23]: I think we can stick with`~> 1.2` and use `allow_pre: false`, can't we?

https://hexdocs.pm/elixir/Version.html

**Comment by doomspork** [comment]
Sorry for the delays @sudostack, started a new job recently and it's keeping me busy 😀 

One final comment and this is good to merge.  Thanks again for your help!

**Comment by wulymammoth** [comment]
@doomspork no worries, Sean! You maintain a ton of projects, too, and congrats! :)

File: mix.exs (hunk 1 above)
Comment (wulymammoth) [reply mix.exs:23]: I'll test this out when I get a chance a bit later today, but not sure it's going to work, because the code changes expect that `attrs/1` and `params/1` be under `Mix.Phoenix.Schema` and not `Mix.Phoenix` anymore...

Comment (wulymammoth) [reply mix.exs:23]: Just as I suspected. The specs fail when attempting to do stick to `~> 1.2` with `allow_pre: false` 

How would you like to proceed?

Comment (doomspork) [reply mix.exs:23]: We'll keep what you have @sudostack 👍

**Comment by doomspork** [comment]
Thank you again @sudostack 👍
